---
title: "MD_Analysis_age"
author: "Leng Seong Che & Casey F. Breen"
date: "2026-01-25"
output: pdf_document
---

```{r setup, include=FALSE, set.seed(8287)}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, cache = TRUE)
```

```{r}
library(here)
library(readr)
library(dplyr)
library(ggplot2)
library(MASS) 
library(lubridate)
library(caret)
library(splines)
library(glmnet)
library(tidyr)
library(kableExtra)
library(brms)
```

```{r}
MD_aggregate_year_age_cause <- read_csv(here("data", "Mortality data", "Aggregate cause-specific files", "MD_aggregate_year-age-cause - v1.csv"))
MD_deaths <- read_csv(here("data", "Mortality data", "Granular death count files", "MD_deaths - v1.csv"))
MD_pop <- read_csv(here("data", "Denominator data", "Census counts", "MD_population - v1.csv"))
MD_soldiers <- read_csv(here("data", "Denominator data", "Drafted soldier counts", "MD_soldiers - v1.csv"))
```

# Total Monthly Deaths
```{r}
MD_deaths_clean <- MD_deaths %>%
  mutate(
    date = as.Date(date),
    ym   = floor_date(date, "month")
  ) %>%
  filter(!is.na(age), age >= 0) %>% # drop missing age cases (813/86123 = 0.009)
  mutate(
    age_cat = cut(
      age,
      breaks = c(seq(0, 90, by = 5), Inf),
      right = FALSE,
      labels = c(
        paste(seq(0, 85, by = 5), seq(4, 89, by = 5), sep = "-"),
        "90+"
      )
    )
  )

death_month <- MD_deaths_clean %>%
  group_by(ym, age_cat) %>%
  summarise(monthly_deaths = sum(deaths, na.rm = TRUE), .groups = "drop")
```

# Weather 

## Humidity

```{r}
MD_weather <- read_csv(here("data", "Weather data", "MD_weather - v1.csv"))
```

```{r}
precip_month <- MD_weather %>%
  mutate(ym = as.Date(sprintf("%04d-%02d-01", year, month))) %>%
  group_by(ym) %>%
  summarise(precip = mean(precipitation1, na.rm = TRUE), .groups = "drop")

precip_month <- death_month %>% 
  mutate(year = year(ym), month = month(ym))%>% 
  left_join(precip_month, by = "ym")

precip_month <- precip_month %>%                    
  group_by(month) %>%
  mutate(
    mean_precip_month = mean(precip, na.rm = TRUE),
    sd_precip_month   = sd(precip,   na.rm = TRUE),
    high_precip = ifelse(precip > mean_precip_month, 1, 0),
    very_high_precip = ifelse(precip > mean_precip_month + sd_precip_month, 1, 0)
  ) %>%
  ungroup()
```

## Temperature

```{r}
temp_month <- MD_weather %>%
  mutate(ym = as.Date(sprintf("%04d-%02d-01", year, month))) %>%
  group_by(ym) %>%
  summarise(monthly_mean_temp = mean(temperature1, na.rm = TRUE), 
            monthly_mean_avg_temp = mean(temperature2, na.rm = TRUE),
            .groups = "drop")

temp_month <- death_month %>% 
  mutate(year = year(ym), month = month(ym))%>% 
  left_join(temp_month, by = "ym")

temp_month <- temp_month %>%                    
  group_by(month) %>%
  mutate(
    mean_temp_month = mean(monthly_mean_temp, na.rm = TRUE),
    mean_avg_temp_month = mean(monthly_mean_avg_temp, na.rm = TRUE),
    sd_temp_month   = sd(monthly_mean_temp,   na.rm = TRUE),
    sd_avg_temp_month = sd(monthly_mean_avg_temp, na.rm = TRUE),
    high_temp = ifelse(monthly_mean_temp > mean_temp_month, 1, 0),
    very_high_temp = ifelse(monthly_mean_temp > mean_temp_month + sd_temp_month, 1, 0),
    high_avg_temp = ifelse(monthly_mean_avg_temp > mean_avg_temp_month, 1, 0),
    very_high_avg_temp = ifelse(monthly_mean_avg_temp > mean_avg_temp_month + sd_avg_temp_month, 1, 0)
  ) %>%
  ungroup()
```

# CDR

```{r}
MD_pop_age <- MD_pop %>%
  filter(!is.na(age), age >= 0) %>%
  mutate(
    age_cat = cut(
      age,
      breaks = c(seq(0, 90, by = 5), Inf),
      right = FALSE,
      labels = c(
        paste(seq(0, 85, by = 5), seq(4, 89, by = 5), sep = "-"),
        "90+"
      )
    )
  )

MD_pop_age <- MD_pop_age %>%
  group_by(year, age_cat) %>%
  summarise(pop = sum(population, na.rm = TRUE), .groups = "drop")
```

```{r}
decimal_year <- function(d) { d <- as.Date(d); year(d) + (month(d) - 0.5)/12 }

months_seq <- seq(
  min(death_month$ym),
  max(death_month$ym),
  by = "month"
)

pop_MD_age_month <- MD_pop_age %>%
  group_by(age_cat) %>%
  do({
    data.frame(
      ym = months_seq,
      age_cat = unique(.$age_cat),
      pop = exp(approx(
        x = .$year,
        y = log(.$pop),
        xout = decimal_year(months_seq),
        rule = 2
      )$y)
    )
  }) %>%
  ungroup()

death_month <- death_month %>%
  left_join(
    pop_MD_age_month,
    by = c("ym", "age_cat")
  )

death_month <- death_month %>%
  mutate(
    cdr_per_100k = monthly_deaths / pop * 1e5
  )


ggplot(death_month, aes(x = ym, y = cdr_per_100k, color = age_cat)) +
  geom_line(alpha = 0.7) +
  labs(
    x = "Month",
    y = "Crude death rate per 100,000",
    title = "Monthly crude death rates by age group (Rural Maryland)"
  ) +
  theme_minimal()

ggplot(death_month, aes(x = ym, y = cdr_per_100k)) +
  geom_line(color = "steelblue", linewidth = 0.4) +
  facet_wrap(~ age_cat, scales = "free_y", ncol = 4) +
  labs(
    x = "Month",
    y = "Crude death rate per 100,000",
    title = "Monthly crude death rates by age group (Rural Maryland)"
  ) +
  theme_minimal() +
  theme(
    strip.text = element_text(size = 9),
    axis.text.x = element_text(size = 8)
  )

```

# Modeling

```{r}
month_tab <- precip_month %>%
  left_join(
    temp_month %>%
      dplyr::select(-"ym",-"monthly_deaths" ),
    by = c("year", "month","age_cat"))%>%
  mutate(month_f = factor(month, levels = 1:12, labels = month.abb))

month_tab <- month_tab %>%
  left_join(
    death_month %>%
      dplyr::select(-"monthly_deaths"),
    by = c("ym","age_cat"))

```


## pre pandemic

### OLS

```{r}
train <- month_tab %>% filter(year <= 1916)
test  <- month_tab %>% filter(ym >= as.Date("1917-01-01") & ym <= as.Date("1918-02-01"))

mod_1 <- lm( monthly_deaths ~ month_f + age_cat, data = train)
mod_2 <- lm( monthly_deaths ~ month_f + age_cat + pop, data = train)
mod_3 <- lm( monthly_deaths ~ month_f + age_cat + pop + high_temp , data = train)
mod_4 <- lm( monthly_deaths ~ month_f + age_cat + pop + high_temp + high_precip, data = train)
mod_5 <- lm( monthly_deaths ~ month_f + age_cat + pop + high_temp * high_precip , data = train)
mod_6 <- lm( monthly_deaths ~  month_f + age_cat + pop + monthly_mean_temp + high_temp + very_high_temp + 
              monthly_mean_avg_temp + high_avg_temp + very_high_avg_temp + precip + high_precip + very_high_precip, data = train)

test <- test %>%
  mutate(pred_mod1 = predict(mod_1, newdata = test, type="response"))

test <- test %>%
  mutate(pred_mod2 = predict(mod_2, newdata = test), type="response")

test <- test %>%
  mutate(pred_mod3 = predict(mod_3, newdata = test, type="response"))

test <- test %>%
  mutate(pred_mod4 = predict(mod_4, newdata = test, type="response"))

test <- test %>%
  mutate(pred_mod5 = predict(mod_5, newdata = test, type="response"))

test <- test %>%
  mutate(pred_mod6 = predict(mod_6, newdata = test, type="response"))

rmse <- function(y, yhat) sqrt(mean((y - yhat)^2, na.rm = TRUE))

rmse_mod1 <- rmse(test$monthly_deaths, test$pred_mod1)
rmse_mod2 <- rmse(test$monthly_deaths, test$pred_mod2)
rmse_mod3 <- rmse(test$monthly_deaths, test$pred_mod3)
rmse_mod4 <- rmse(test$monthly_deaths, test$pred_mod4)
rmse_mod5 <- rmse(test$monthly_deaths, test$pred_mod5)
rmse_mod6 <- rmse(test$monthly_deaths, test$pred_mod6)

rmse_mod1;rmse_mod2;rmse_mod3;rmse_mod4;rmse_mod5;rmse_mod6
```

```{r}
set.seed(8287)
###### CV ###
cv_5fold <- trainControl(method = "cv", number = 5)

cv_rmse_mod1 <- train(monthly_deaths ~ month_f + age_cat , data = train, method = "lm", trControl = cv_5fold)$results$RMSE
cv_rmse_mod2 <- train(monthly_deaths ~ month_f + age_cat + log(pop) , data = train, method = "lm", trControl = cv_5fold)$results$RMSE
cv_rmse_mod3 <- train(monthly_deaths ~ month_f + age_cat + log(pop) + high_temp , data = train, method = "lm", trControl = cv_5fold)$results$RMSE
cv_rmse_mod4 <- train(monthly_deaths ~ month_f + age_cat + log(pop) + high_temp + high_precip , data = train, method = "lm", trControl = cv_5fold)$results$RMSE 
cv_rmse_mod5 <- train(monthly_deaths ~ month_f + age_cat + log(pop) + high_temp * high_precip , data = train, method = "lm", trControl = cv_5fold)$results$RMSE 
cv_rmse_mod6 <- train(monthly_deaths ~ month_f + age_cat + log(pop) + monthly_mean_temp + high_temp + very_high_temp + 
              monthly_mean_avg_temp + high_avg_temp + very_high_avg_temp + precip + high_precip + very_high_precip, 
      data = train, method = "lm", trControl = cv_5fold)$results$RMSE

cv_rmse_mod1;cv_rmse_mod2;cv_rmse_mod3;cv_rmse_mod4;cv_rmse_mod5;cv_rmse_mod6

```

### lasso

```{r}
set.seed(8287)
form <- monthly_deaths ~ month_f  + age_cat + log(pop) + 
  monthly_mean_temp + high_temp + very_high_temp +
  monthly_mean_avg_temp + high_avg_temp + very_high_avg_temp +
  precip + high_precip + very_high_precip

#### lasso ####
x_train <- model.matrix(form, data = train)[, -1]
y_train <- train$monthly_deaths

x_test  <- model.matrix(form, data = test)[, -1]
y_test  <- test$monthly_deaths

cv_lasso <- cv.glmnet(x_train, y_train, alpha = 1, family = "gaussian", nfolds = 5)

lambda_lasso_min <- cv_lasso$lambda.min
lambda_lasso_1se <- cv_lasso$lambda.1se

pred_lasso_min <- predict(cv_lasso, s = lambda_lasso_min, newx = x_test)

cv_rmse_lasso <- sqrt(min(cv_lasso$cvm))
rmse_lasso <- rmse(y_test, pred_lasso_min)
# coef(cv_lasso, s = cv_lasso$lambda.min)

cv_rmse_lasso
rmse_lasso
```

### Bayesian

#### Poisson 

```{r}
fit_poi <- brm(monthly_deaths ~ month_f + (1 | age_cat) + offset(log(pop)),
  data   = train,
  family = poisson(),
  chains = 4, cores = 4, seed = 8287
)

fit_all <- brm(monthly_deaths ~ month_f + (1 | age_cat) + offset(log(pop))+ log(pop) + monthly_mean_temp + high_temp + very_high_temp + 
              monthly_mean_avg_temp + high_avg_temp + very_high_avg_temp + precip + high_precip + very_high_precip,
  data   = train,
  family = poisson(),
  chains = 4, cores = 4, seed = 8287
)

fit_selected_poi <- brm(monthly_deaths ~ month_f + (1 | age_cat) + offset(log(pop))+ log(pop) + monthly_mean_temp + high_temp + very_high_temp + 
              monthly_mean_avg_temp + very_high_avg_temp + precip + high_precip + very_high_precip,
  data   = train,
  family = poisson(),
  chains = 4, cores = 4, seed = 8287
)

test <- test %>%
  mutate(pred_mod_b_poi =fitted(fit_poi, newdata = test)[, "Estimate"])

test <- test %>%
  mutate(pred_mod_b_poi_all =fitted(fit_all, newdata = test)[, "Estimate"])

test <- test %>%
  mutate(pred_mod_b_poi_selected =fitted(fit_selected_poi, newdata = test)[, "Estimate"])


rmse_mod_b_poi <- rmse(test$monthly_deaths, test$pred_mod_b_poi)
rmse_mod_b_poi_all <- rmse(test$monthly_deaths, test$pred_mod_b_poi_all)
rmse_mod_b_poi_selected <- rmse(test$monthly_deaths, test$pred_mod_b_poi_selected)

rmse_mod_b_poi;rmse_mod_b_poi_all;rmse_mod_b_poi_selected
```

```{r}
fit_nb <- brm(monthly_deaths ~ month_f + (1 | age_cat) + offset(log(pop)),
  data   = train,
  family = negbinomial(),
  chains = 4, cores = 4, seed = 8287
)

fit_nb_all <- brm(monthly_deaths ~  month_f + (1 | age_cat) + offset(log(pop))+ log(pop) + monthly_mean_temp + high_temp + very_high_temp + 
              monthly_mean_avg_temp + high_avg_temp + very_high_avg_temp + precip + high_precip + very_high_precip,
  data   = train,
  family = negbinomial(),
  chains = 4, cores = 4, seed = 8287
)

fit_nb_selected <- brm(monthly_deaths ~  month_f + (1 | age_cat) + offset(log(pop))+ log(pop) + high_temp + very_high_temp + 
              monthly_mean_avg_temp + high_avg_temp + very_high_avg_temp + precip + high_precip + very_high_precip,
  data   = train,
  family = negbinomial(),
  chains = 4, cores = 4, seed = 8287
)

test <- test %>%
  mutate(pred_mod_b_nb =fitted(fit_nb, newdata = test)[, "Estimate"])

test <- test %>%
  mutate(pred_mod_b_nb_all =fitted(fit_nb_all, newdata = test)[, "Estimate"])

test <- test %>%
  mutate(pred_mod_b_nb_selected =fitted(fit_nb_selected, newdata = test)[, "Estimate"])

rmse_mod_b_nb <- rmse(test$monthly_deaths, test$pred_mod_b_nb)
rmse_mod_b_nb_all <- rmse(test$monthly_deaths, test$pred_mod_b_nb_all)
rmse_mod_b_nb_selected <- rmse(test$monthly_deaths, test$pred_mod_b_nb_selected)

rmse_mod_b_nb;rmse_mod_b_nb_all;rmse_mod_b_nb_selected
```

```{r}
rmse_tab <- data.frame(
  Model    = c("OLS_short", "OLS_full", "Lasso", "b_Poisson_naive", "b_NegBin_naive", "b_Poisson_all", "b_NegBin_all", "b_NegBin_selected", "b_Poisson_selected"),
  CV_RMSE  = round(c(cv_rmse_mod1, cv_rmse_mod6, cv_rmse_lasso, NA, NA, NA, NA, NA, NA), 2),
  Test_RMSE = round(c(rmse_mod1, rmse_mod6, rmse_lasso, rmse_mod_b_poi, rmse_mod_b_nb, rmse_mod_b_poi_all,
                      rmse_mod_b_nb_all,rmse_mod_b_nb_selected, rmse_mod_b_poi_selected), 2)
)

kable(rmse_tab, caption = "5-Fold CV and Test RMSEs")
```

## Pandemic

```{r}
train <- month_tab %>% filter(year <= 1916)
test_pandemic  <- month_tab %>% filter(ym >= as.Date("1918-02-01") & ym <= as.Date("1920-05-01"))

xtest <- model.matrix(form, data = test_pandemic)[, -1]
test_pandemic <- test_pandemic %>%
  mutate(
    pred_ols = predict(mod_1, newdata = test_pandemic, type="response"),
    pred_ols_full = predict(mod_6, newdata = test_pandemic, type="response"), ### mod_6 #### 
    pred_lasso = as.numeric(predict(cv_lasso, s = lambda_lasso_min, newx = xtest)), ### lasso ###
    pred_mod_b_poi_naive = fitted(fit_poi, newdata = test_pandemic)[, "Estimate"],
    pred_mod_b_nb_naive = fitted(fit_nb, newdata = test_pandemic)[, "Estimate"],
    pred_mod_b_poi_all = fitted(fit_all, newdata = test_pandemic)[, "Estimate"],
    pred_mod_b_nb_all = fitted(fit_nb_all, newdata = test_pandemic)[, "Estimate"],
    pred_mod_b_nb_selected = fitted(fit_nb_selected, newdata = test_pandemic)[, "Estimate"],
    pred_mod_b_poi_selected = fitted(fit_selected_poi, newdata = test_pandemic)[, "Estimate"]
    )

```

```{r}
excess_df <- test_pandemic %>%
  mutate(
    excess_ols       = monthly_deaths - pred_ols,
    excess_ols_full  = monthly_deaths - pred_ols_full,
    excess_lasso     = monthly_deaths - pred_lasso,
    excess_b_poisson_naive = monthly_deaths - pred_mod_b_poi_naive,
    excess_b_NegBin_naive       = monthly_deaths - pred_mod_b_nb_naive,
    excess_b_poisson       = monthly_deaths - pred_mod_b_poi_all,
    excess_b_NegBin       = monthly_deaths - pred_mod_b_nb_all,
    excess_b_NegBin_selected       = monthly_deaths - pred_mod_b_nb_selected,
    excess_b_poisson_selected       = monthly_deaths - pred_mod_b_poi_selected
  )

total_excess <- summarise(excess_df,
  OLS             = sum(excess_ols,      na.rm = TRUE),
  OLS_full        = sum(excess_ols_full, na.rm = TRUE),
  Lasso           = sum(excess_lasso,    na.rm = TRUE),
  b_poisson_naive       = sum(excess_b_poisson_naive,      na.rm = TRUE),
  b_NegBin_naive       = sum(excess_b_NegBin_naive,      na.rm = TRUE),  
  b_poisson       = sum(excess_b_poisson,      na.rm = TRUE),
  b_NegBin        = sum(excess_b_NegBin,      na.rm = TRUE),
  b_NegBin_selected        = sum(excess_b_NegBin_selected,      na.rm = TRUE),
  b_poisson_selected       = sum(excess_b_poisson_selected,      na.rm = TRUE)
) %>% tidyr::pivot_longer(everything(), names_to="Model", values_to="Estimated_Total_Excess")

kable(total_excess, caption = "Excess Mortality Estimates")%>%
  kable_styling(latex_options = c("hold_position"))
```

```{r}
set.seed(8287)
# predict using Bayesian negative binomial model (all predictors)
epred_nb <- posterior_predict(fit_nb_all, newdata = test_pandemic)

# indices of rows belonging to each age group
idx_by_age <- split(seq_len(nrow(test_pandemic)), test_pandemic$age_cat)

# compute excess deaths per draw, per age group
total_excess_draw_nb_age <- lapply(idx_by_age, function(x) {
  apply(epred_nb[, x, drop = FALSE], 1, function(mu) {
    sum(test_pandemic$monthly_deaths[x] - mu)
  })
})

# adjust for missingness
adj_missing <- 1 / (1- sum(is.na(MD_deaths$age))/nrow(MD_deaths))

results_age <- data.frame(
  age_cat = names(total_excess_draw_nb_age),
  mean = sapply(total_excess_draw_nb_age, mean) * adj_missing,
  lwr  = sapply(total_excess_draw_nb_age, quantile, 0.025) * adj_missing,
  upr  = sapply(total_excess_draw_nb_age, quantile, 0.975) * adj_missing
)

results_age
```


```{r}
age_pandemic_pop <- death_month %>%
  filter(ym >= as.Date("1918-03-01") & ym <= as.Date("1920-05-01")) %>%
  group_by(age_cat) %>%
  summarise(
    pop_sum = sum(pop),
    .groups = "drop"
  )

results_age <- results_age %>%
  left_join(age_pandemic_pop, by = "age_cat")

results_age <- results_age %>%
  mutate(
    rate_mean = mean / pop_sum * 1e5,
    rate_lwr  = lwr  / pop_sum * 1e5,
    rate_upr  = upr  / pop_sum * 1e5
  )

results_age
```

```{r}
# export data
# write.csv(results_age, file = 'MD_age_table.csv', row.names = FALSE)
# 
# write.csv(rmse_tab, file = 'MD_age_model_eval.csv', row.names = FALSE)
# 
# write.csv(total_excess, file = 'MD_age_excess.csv', row.names = FALSE)
```

